### ISSUE TITLE
manager奇怪的崩溃问题

### ISSUE THREAD

**Issue by 3titep** [MiPushFramework/MiPushFramework#258]
**Describe the bug/**
manager在某种情况下一进入就崩溃，重装manager/push，清除app数据，退回旧版都不能解决问题

**To Reproduce**
本来想改一个去掉”小米推送运行中“常驻消息的版本自用，在反复安装原版/改版的过程中出现此问题，复现原因未知

**Expected behavior**
A clear and concise description of what you expected to happen.（您希望发生什么）

**Screenshots**（截图）

**Logs** （日志）
adb logcat:
02-06 13:24:00.022 31797 31797 E AndroidRuntime: FATAL EXCEPTION: main
02-06 13:24:00.022 31797 31797 E AndroidRuntime: Process: top.trumeet.mipush, PID: 31797
02-06 13:24:00.022 31797 31797 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.SwitchCompat.setEnabled(boolean)' on a null object reference
02-06 13:24:00.022 31797 31797 E AndroidRuntime:        at top.trumeet.mipushframework.MainFragment.refreshStatus(MainFragment.java:198)
02-06 13:24:00.022 31797 31797 E AndroidRuntime:        at top.trumeet.mipushframework.MainFragment.onChange(MainFragment.java:213)
02-06 13:24:00.022 31797 31797 E AndroidRuntime:        at top.trumeet.mipushframework.MainActivity$ConnectTask$1.onReady(MainActivity.java:171)
02-06 13:24:00.022 31797 31797 E AndroidRuntime:        at top.trumeet.common.push.ControllerImpl$$Lambda$0.run(Unknown Source)
02-06 13:24:00.022 31797 31797 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
02-06 13:24:00.022 31797 31797 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
02-06 13:24:00.022 31797 31797 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
02-06 13:24:00.022 31797 31797 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6314)
02-06 13:24:00.022 31797 31797 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-06 13:24:00.022 31797 31797 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
02-06 13:24:00.022 31797 31797 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

**ROM and version(manager):** （你的 ROM 和 manager 的版本）
 - Name: LG OS
 - Android Version: 7.0
 - Version 0.3.6.20190128.b0fe719

**Additional context**
根据logcat提示，将MainFragment.java第198行
        mSwitchEnablePush.setEnabled(true);
注释掉就可以运行了，猜想可能此特殊情况下执行次序出了问题

![honeyview_screenshot_2019-02-06-13-30-54](https://user-images.githubusercontent.com/47377982/52324851-e079af00-2a1d-11e9-8658-7b3003b90fd9.jpg)
![honeyview_screenshot_2019-02-06-13-44-58](https://user-images.githubusercontent.com/47377982/52324860-eb344400-2a1d-11e9-9fe3-7786d5b9f49a.jpg)

**Comment by TimothyZhang023** [comment]
这里一直有问题的 @Trumeet  特别是Push stop之后容易触发这个。。
