### ISSUE TITLE
Manager 在 Android 7.1.2 崩溃

### ISSUE THREAD

**Issue by StarWishsama** [MiPushFramework/MiPushFramework#265]
**Describe the bug/**
A clear and concise description of what the bug is.（解释一下出了什么问题）
Manager 打开时崩溃。

**To Reproduce**
Steps to reproduce the behavior:（如何复现错误，也就是您的操作步骤）
1. 正常安装 Manager
2. 打开 Manager

**Expected behavior**
A clear and concise description of what you expected to happen.（您希望发生什么）
正常进入 Manager

**Screenshots**（截图）

**Logs** （日志）
Logs are very important, this can help us solve the problem.
Please upload your log file and paste the address here:（请上传您的日志文件，在这里粘贴地址：）
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setEnabled(boolean)' on a null object reference
	at top.trumeet.mipushframework.MainFragment.refreshStatus(MainFragment.java:198)
	at top.trumeet.mipushframework.MainFragment.onChange(MainFragment.java:213)
	at top.trumeet.mipushframework.MainActivity$ConnectTask$1.onReady(MainActivity.java:171)
	at top.trumeet.common.push.ControllerImpl$$Lambda$0.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

**ROM and version(manager):** （你的 ROM 和 manager 的版本）
 - Name: Lineage OS
 - Android Version: 7.1.2
 - Version: 0.3.6.20190128

**Additional context**
Add any other context about the problem here.（更多关于问题的内容写在这里）

**Comment by TimothyZhang023** [comment]
一直重启还是 偶现

**Comment by StarWishsama** [comment]
偶现

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Timothy Zhang <notifications@github.com>
发送时间: Wednesday, April 10, 2019 12:03:07 PM
收件人: MiPushFramework/MiPushFramework
抄送: StarWishSama; Author
主题: Re: [MiPushFramework/MiPushFramework] Manager 在 Android 7.1.2 崩溃 (#265)


一直重启还是 偶现

―

**Comment by heipidage** [comment]
我也有 似乎是在安装了新应用后 打开manager容易出现。但是不好重先。暂时先把manager放入电池优化白名单，不黑域。限制其自启动引起的？？

**Comment by TimothyZhang023** [comment]
已知问题。
