### ISSUE TITLE
一点开manager就闪退

### ISSUE THREAD

**Issue by holmium** [MiPushFramework/MiPushFramework#284]
**Describe the bug/**
闪退

**To Reproduce**
打开直接闪退

**Expected behavior**
当然是不闪退

**Screenshots**（截图）
闪退了没法截图

**Logs** （日志）
08-08 08:50:15.343 17292 17292 E AndroidRuntime: Process: top.trumeet.mipush, PID: 17292
08-08 08:50:15.343 17292 17292 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.SwitchCompat.setEnabled(boolean)' on a null object reference
08-08 08:50:15.343 17292 17292 E AndroidRuntime:        at top.trumeet.mipushframework.MainFragment.refreshStatus(MainFragment.java:198)
08-08 08:50:15.343 17292 17292 E AndroidRuntime:        at top.trumeet.mipushframework.MainFragment.onChange(MainFragment.java:213)
08-08 08:50:15.343 17292 17292 E AndroidRuntime:        at top.trumeet.mipushframework.MainActivity$ConnectTask$1.onReady(MainActivity.java:171)
08-08 08:50:15.343 17292 17292 E AndroidRuntime:        at top.trumeet.common.push.ControllerImpl$$Lambda$0.run(Unknown Source:2)
08-08 08:50:15.343 17292 17292 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
08-08 08:50:15.343 17292 17292 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
08-08 08:50:15.343 17292 17292 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
08-08 08:50:15.343 17292 17292 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6718)
08-08 08:50:15.343 17292 17292 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-08 08:50:15.343 17292 17292 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-08 08:50:15.343 17292 17292 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**ROM and version(manager):** （你的 ROM 和 manager 的版本）
 - Name: [e.g. Lineage OS]
 - Android Version: [e.g. 8.1]
 - Version [e.g. 0.3.4 stable]
魔趣每夜版，安卓9，MiPush最新pre release 版

**Additional context**

**Comment by TimothyZhang023** [comment]
manager 装了同一个版本还是 crash么？

**Comment by holmium** [comment]
应该是我把系统动画关闭的原因，导致某些控件提前渲染。
