### ISSUE TITLE
最新版本不能正常推送

### ISSUE THREAD

**Issue by mokapsing** [MiPushFramework/MiPushFramework#285]
**Describe the bug/**
A clear and concise description of what the bug is.（解释一下出了什么问题）
之前正常推送的app，这一版本记录里面有通知，但是状态栏没提示
**To Reproduce**
Steps to reproduce the behavior:（如何复现错误，也就是您的操作步骤）
1. 正常安装新版本
2. na
3. na

**Expected behavior**
A clear and concise description of what you expected to happen.（您希望发生什么）
当然是像上一版本一样正常push
**Screenshots**（截图）

**Logs** （日志）
Logs are very important, this can help us solve the problem.
Please upload your log file and paste the address here:（请上传您的日志文件，在这里粘贴地址：）
[logs-2019-03-14-9-3-47.zip](https://github.com/MiPushFramework/MiPushFramework/files/3501685/logs-2019-03-14-9-3-47.zip)
**ROM and version(manager):** （你的 ROM 和 manager 的版本）
 - Name: [e.g. Lineage OS] Samsung One UI
 - Android Version: [e.g. 8.1] 9.0
 - Version [e.g. 0.3.4 stable] n/a

**Additional context**
Add any other context about the problem here.（更多关于问题的内容写在这里）

**Comment by LastEight** [comment]
同样的问题，关注一下

**Comment by baillob** [comment]
同 Samsung One UI，20190804版本记录看见，但是状态栏没通知。退回20190429版本正常

**Comment by ViolentBanana** [comment]
看来不止是我了。三星one UI 准备回退旧版本了

**Comment by hu-hc** [comment]
确实只在One UI上出问题，AOSP上可以正常推送。

**Comment by TimothyZhang023** [comment]
@oasisfeng  看上去

**Comment by TimothyZhang023** [comment]
```
1565739336103|E|MyClientEventDispatcherD|java.lang.AbstractMethodError: abstract method "android.graphics.drawable.Drawable android.content.pm.PackageManager.loadItemIcon(android.content.pm.PackageItemInfo, android.content.pm.ApplicationInfo, boolean, int)"
	at android.content.pm.PackageItemInfo.loadIcon(PackageItemInfo.java:537)
	at android.content.pm.PackageItemInfo.loadIcon(PackageItemInfo.java:530)
	at top.trumeet.common.cache.IconCache$1.gen(IconCache.java:55)
	at top.trumeet.common.cache.IconCache$1.gen(IconCache.java:50)
	at top.trumeet.common.cache.AbstractCacheAspect.get(AbstractCacheAspect.java:18)
	at top.trumeet.common.cache.IconCache.getRawIconBitmap(IconCache.java:61)
	at top.trumeet.common.cache.IconCache$2.gen(IconCache.java:68)
	at top.trumeet.common.cache.IconCache$2.gen(IconCache.java:65)
	at top.trumeet.common.cache.AbstractCacheAspect.get(AbstractCacheAspect.java:18)
	at top.trumeet.common.cache.IconCache.getIconCache(IconCache.java:72)
	at com.xiaomi.xmsf.push.notification.NotificationController.processSmallIcon(NotificationController.java:244)
	at com.xiaomi.push.service.MyMIPushNotificationHelper.notifyPushMessage(MyMIPushNotificationHelper.java:67)
	at com.xiaomi.push.service.MyMIPushMessageProcessor.userProcessMIPushMessage(MyMIPushMessageProcessor.java:217)
	at com.xiaomi.push.service.MyMIPushMessageProcessor.process(MyMIPushMessageProcessor.java:124)
	at com.xiaomi.push.service.MyClientEventDispatcher$EventProcessor.runProcessMIPushMessage(MyClientEventDispatcher.java:139)
	at com.xiaomi.push.service.MyClientEventDispatcher$EventProcessor.processNewPacket(MyClientEventDispatcher.java:151)
	at com.xiaomi.push.service.ClientEventDispatcher.notifyPacketArrival(Unknown Source:45)
	at com.xiaomi.push.service.MyClientEventDispatcher.notifyPacketArrival(MyClientEventDispatcher.java:87)
	at com.xiaomi.push.service.PacketSync.handleBlob(Unknown Source:50)
	at com.xiaomi.push.service.PacketSync.onBlobReceive(Unknown Source:10)
	at com.xiaomi.push.service.XMPushService$BlobReceiveJob.process(Unknown Source:8)
	at com.xiaomi.push.service.XMPushService$Job.run(Unknown Source:37)
	at com.xiaomi.push.service.JobScheduler$SchedulerImpl.run(Unknown Source:175)

```

loadItemIcon不知道是不是有兼容性问题？

**Comment by oasisfeng** [comment]
没有遇到过这个问题，`loadIcon()` 是 Android 从第一天开始就一直存在的 API，OneUI 按理说不可能存在这么低级的兼容性问题。

更奇怪的是，报 `AbstractMethodError` 的 `loadItemIcon()` 是被 `loadIcon()` 这个 public API 调用的，而不是 app 代码调用的……

**Comment by TimothyZhang023** [comment]
AbstractMethodError 接不住，然后gg了。。


@oasisfeng  我看确实有点奇怪，这个签名好像和sdk不一样，参数多了？
android.graphics.drawable.Drawable android.content.pm.PackageManager.loadItemIcon(android.content.pm.PackageItemInfo, android.content.pm.ApplicationInfo, boolean, int)

**Comment by oasisfeng** [comment]
@TimothyZhang023 应该是被三星魔改过，加了一个 private overload 方法……

看来只能 catch 这个异常，fallback 里调用 getApplicationIcon(ApplicationInfo info)？

**Comment by TimothyZhang023** [comment]
> fallback

只能做个兜底兼容了

**Comment by TimothyZhang023** [comment]
#293

**Comment by TimothyZhang023** [comment]
fix了
