### ISSUE TITLE
Android 10支援

### ISSUE THREAD

**Issue by ChenYuWuAi** [MiPushFramework/MiPushFramework#290]
Android10无法正常使用，没推送

**Comment by fgprodigal** [comment]
无法注册，也收不到推送

**Comment by moonheart** [comment]
日志中大量这样的错误
```
1568438281022|E|XMPushService Bridge|XMPushService::onHandleIntent: 
java.lang.IllegalArgumentException: Unknown URL content://top.trumeet.mipush.providers.AppProvider/RegisteredApplication
	at android.content.ContentResolver.insert(ContentResolver.java:1850)
	at top.trumeet.common.utils.DatabaseUtils.insert(DatabaseUtils.java:31)
	at top.trumeet.common.db.RegisteredApplicationDb.insert(RegisteredApplicationDb.java:98)
	at top.trumeet.common.db.RegisteredApplicationDb.create(RegisteredApplicationDb.java:88)
	at top.trumeet.common.db.RegisteredApplicationDb.registerApplication(RegisteredApplicationDb.java:45)
	at com.xiaomi.xmsf.push.service.XMPushService.onHandleIntent(XMPushService.java:57)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by kongdeli** [comment]
[logs-2019-31-24-9-31-9.zip](https://github.com/MiPushFramework/MiPushFramework/files/3644807/logs-2019-31-24-9-31-9.zip)

@TimothyZhang023 Android 10 日志

**Comment by Wickscc** [comment]
出现同样的问题
`1570502064264|E|XMPushService Bridge|XMPushService::onHandleIntent: 
java.lang.IllegalArgumentException: Unknown URL content://top.trumeet.mipush.providers.AppProvider/RegisteredApplication
	at android.content.ContentResolver.insert(ContentResolver.java:1824)
	at top.trumeet.common.utils.DatabaseUtils.insert(DatabaseUtils.java:31)
	at top.trumeet.common.db.RegisteredApplicationDb.insert(RegisteredApplicationDb.java:98)
	at top.trumeet.common.db.RegisteredApplicationDb.create(RegisteredApplicationDb.java:88)
	at top.trumeet.common.db.RegisteredApplicationDb.registerApplication(RegisteredApplicationDb.java:45)
	at com.xiaomi.xmsf.push.service.XMPushService.onHandleIntent(XMPushService.java:57)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:67)`

**Comment by TimothyZhang023** [comment]
@Trumeet  emmm 你的 =8pro有问题么

**Comment by ProphetCai** [comment]
我的安卓q也不能用

**Comment by dvtc** [comment]
@TimothyZhang023 我的=8pro也无法注册

**Comment by snipking** [comment]
=8pro 同样问题

Unknown URL content://top.trumeet.mipush.providers.AppProvider/RegisteredApplication

**Comment by TimothyZhang023** [comment]
把两个app 都加入电池优化白名单呢？

**Comment by snipking** [comment]
@TimothyZhang023 试过了，无效，这个问题和电池优化没关系吧？在 Apps & notifications -> Default apps -> Opening links 里面没有看到 Push 或 MiPush Framework 关联 top.trumeet.mipush.providers.AppProvider 这个域名

**Comment by Wickscc** [comment]
> 这个事情神奇就神奇在，太极里勾上push模块，就能用了

勾上了倒是有反应了,但是注册异常

**Comment by nictse2013** [comment]
已经更新了，谁测试下Q能用么？

**Comment by snipking** [comment]
@nictse2013 最新的版本已经能正常注册和接到推送了，但是拉不起来应用。OS 一加7pro测试第5版

**Comment by snipking** [comment]
@nictse2013 最新的版本已经能正常注册和接到推送了，但是拉不起来应用。OS 一加7pro测试第5版

**Comment by nictse2013** [comment]
> @nictse2013 最新的版本已经能正常注册和接到推送了，~但是拉不起来应用~ 部分应用拉不起来，比如什么值得买，但是微博和高德地图是正常的。一加7pro 氢OS测试第5版

多谢分享 magisk那两个伪装需要安装么？

**Comment by snipking** [comment]
我是安装了的

**Comment by TimothyZhang023** [comment]
done
