### ISSUE TITLE
Android10遇到的崩溃日志

### ISSUE THREAD

**Issue by chenyue404** [MiPushFramework/MiPushFramework#294]
```
FATAL EXCEPTION: main
 Process: com.xiaomi.xmsf:pushservice, PID: 5785
 java.lang.RuntimeException: Unable to start receiver com.xiaomi.xmsf.push.service.receivers.NetworkStatusReceiver: java.lang.NullPointerException: Attempt to invoke interface method 'android.os.Bundle android.content.IContentProvider.call(java.lang.String, java.lang.String, java.lang.String, java.lang.String, android.os.Bundle)' on a null object reference
 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3914)
 	at android.app.ActivityThread.access$1700(ActivityThread.java:231)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1963)
 	at android.os.Handler.dispatchMessage(Handler.java:107)
 	at android.os.Looper.loop(Looper.java:214)
 	at android.app.ActivityThread.main(ActivityThread.java:7682)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
 Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'android.os.Bundle android.content.IContentProvider.call(java.lang.String, java.lang.String, java.lang.String, java.lang.String, android.os.Bundle)' on a null object reference
 	at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:2417)
 	at android.provider.Settings$Global.getStringForUser(Settings.java:14701)
 	at android.provider.Settings$Global.getString(Settings.java:14689)
 	at android.provider.Settings$Global.getInt(Settings.java:14871)
 	at com.xiaomi.push.service.PushProvision.getProvisioned(Unknown Source:22)
 	at com.xiaomi.mipush.sdk.PushServiceClient.isProvisioned(Unknown Source:24)
 	at com.xiaomi.xmsf.push.service.receivers.NetworkStatusReceiver.onReceive(NetworkStatusReceiver.java:18)
 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3900)
 	... 8 more
```
-------
```
FATAL EXCEPTION: AsyncTask #1
 Process: top.trumeet.mipush, PID: 17180
 java.lang.RuntimeException: An error occurred while executing doInBackground()
 	at android.os.AsyncTask$4.done(AsyncTask.java:399)
 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 	at java.lang.Thread.run(Thread.java:919)
 Caused by: java.lang.IllegalArgumentException: Unknown authority com.xiaomi.xmsf.push.control.APIProvider
 	at android.content.ContentResolver.call(ContentResolver.java:2085)
 	at android.content.ContentResolver.call(ContentResolver.java:2068)
 	at top.trumeet.common.push.ControllerImpl.call(ControllerImpl.java:28)
 	at top.trumeet.common.push.ControllerImpl.getVersionCode(ControllerImpl.java:77)
 	at top.trumeet.mipushframework.MainActivity$ConnectTask.doInBackground(MainActivity.java:189)
 	at top.trumeet.mipushframework.MainActivity$ConnectTask.doInBackground(MainActivity.java:146)
 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 	... 4 more
```

**Comment by TimothyZhang023** [comment]
什么rom ，有什么优化拦截软件么？
